package com.chatty.compose.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF455D91)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD9E2FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001A43)
val md_theme_light_secondary = Color(0xFF5A5E6C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDEE2F2)
val md_theme_light_onSecondaryContainer = Color(0xFF171B27)
val md_theme_light_tertiary = Color(0xFF6D586D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF6DAF4)
val md_theme_light_onTertiaryContainer = Color(0xFF261628)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFBFE)
val md_theme_light_onBackground = Color(0xFF1B1B1E)
val md_theme_light_surface = Color(0xFFFEFBFE)
val md_theme_light_onSurface = Color(0xFF1B1B1E)
val md_theme_light_surfaceVariant = Color(0xFFE2E2E9)
val md_theme_light_onSurfaceVariant = Color(0xFF45464C)
val md_theme_light_outline = Color(0xFF76777D)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF303033)
val md_theme_light_inverseOnSurface = Color(0xFFF2F0F3)
val md_theme_light_inversePrimary = Color(0xFFAFC6FF)
val md_theme_light_surfaceTint = Color(0xFF455D91)

val md_theme_dark_primary = Color(0xFFAFC6FF)
val md_theme_dark_onPrimary = Color(0xFF132F60)
val md_theme_dark_primaryContainer = Color(0xFF2D4678)
val md_theme_dark_onPrimaryContainer = Color(0xFFD9E2FF)
val md_theme_dark_secondary = Color(0xFFC2C6D6)
val md_theme_dark_onSecondary = Color(0xFF2C303D)
val md_theme_dark_secondaryContainer = Color(0xFF424754)
val md_theme_dark_onSecondaryContainer = Color(0xFFDEE2F2)
val md_theme_dark_tertiary = Color(0xFFD9BED7)
val md_theme_dark_onTertiary = Color(0xFF3C2A3D)
val md_theme_dark_tertiaryContainer = Color(0xFF544055)
val md_theme_dark_onTertiaryContainer = Color(0xFFF6DAF4)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFB4AB)
val md_theme_dark_background = Color(0xFF1B1B1E)
val md_theme_dark_onBackground = Color(0xFFE4E2E5)
val md_theme_dark_surface = Color(0xFF1B1B1E)
val md_theme_dark_onSurface = Color(0xFFE4E2E5)
val md_theme_dark_surfaceVariant = Color(0xFF45464C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C6CD)
val md_theme_dark_outline = Color(0xFF909097)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFE4E2E5)
val md_theme_dark_inverseOnSurface = Color(0xFF303033)
val md_theme_dark_inversePrimary = Color(0xFF455D91)
val md_theme_dark_surfaceTint = Color(0xFFAFC6FF)


val seed = Color(0xFF92AAE3)


val green = Color(0xFF5AE228)